#!/bin/bash

# Define request parameters
ENDPOINT='https://api.openai.com/v1/chat/completions'
MODEL="gpt-3.5-turbo"
CONTENT="$@"
CONTENT="${CONTENT//\"/\\\"}"

# You can change the prefix by setting the HOW_PREFIX environment variable
[[ ! -z "$HOW_PREFIX" ]] && HOW_PREFIX="$HOW_PREFIX" || HOW_PREFIX="Reply using oneline bash command. Question: How"

DATA="{\"model\": \"$MODEL\", \"temperature\": 0, \"messages\": [{\"role\": \"user\", \"content\": \"$HOW_PREFIX $CONTENT\"}]}"
RESPONSE=$(curl --silent --location --insecure --request POST "$ENDPOINT" \
  --header "Authorization: Bearer $OPENAI_API_KEY" \
  --header 'Content-Type: application/json' \
  --data-raw "$DATA")

# Print the response
MESSAGE_CONTENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
echo "$MESSAGE_CONTENT" # print command to terminal
echo "$MESSAGE_CONTENT" | pbcopy # copy command to clipboard
